"""
Trinity Model Manager — 3-model rotation for multi-candidate generation.

Cross-architecture review catches +35% more bugs by eliminating
"cognitive blindness" where the same model misses the same error class.

Three model roles:
    Architect  — CoT reasoning, planning (deepseek-r1:7b)
    Developer  — Code generation (qwen2.5-coder:7b)
    Reviewer   — Code review, bug detection (deepseek-coder:6.7b-instruct)

Strategies:
    rotate      — round-robin across all models
    role_based  — developer first, then reviewer, then architect
    risk_based  — simple tasks use developer only, complex use all 3
"""

import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


class TrinityRole(str, Enum):
    """Model roles in the Trinity pipeline."""
    ARCHITECT = "architect"    # CoT reasoning, planning, decomposition
    DEVELOPER = "developer"    # Code generation, implementation
    REVIEWER = "reviewer"      # Code review, bug detection, cross-arch


# Default role generation order: developer first (fast), reviewer, architect last
_DEFAULT_ROLE_ORDER = [TrinityRole.DEVELOPER, TrinityRole.REVIEWER, TrinityRole.ARCHITECT]

# Default model mapping (can be overridden via config)
DEFAULT_TRINITY_MODELS: Dict[str, str] = {
    TrinityRole.ARCHITECT: "deepseek-r1:7b",
    TrinityRole.DEVELOPER: "qwen2.5-coder:7b",
    TrinityRole.REVIEWER: "deepseek-coder:6.7b-instruct",
}


class TrinityModelManager:
    """Manages 3-model rotation for multi-candidate generation.

    When enabled, each candidate in the MC pipeline is generated by a
    different model architecture.  The existing 53+ validation rules
    then score all candidates equally — best code wins regardless of
    which model produced it.
    """

    def __init__(
        self,
        models: Dict[str, str],
        strategy: str = "rotate",
    ):
        """
        Args:
            models: Mapping of role name → Ollama model name.
                    e.g. {"architect": "deepseek-r1:7b", ...}
            strategy: Selection strategy — "rotate", "role_based", or "risk_based".
        """
        self.models = models
        self.strategy = strategy
        self._role_order: List[TrinityRole] = list(_DEFAULT_ROLE_ORDER)
        self._stats = {
            "selections": 0,
            "per_model": {m: 0 for m in models.values()},
            "full_pipeline_used": 0,
            "developer_only_used": 0,
        }

    def select_for_candidate(
        self,
        index: int,
        task_context=None,
    ) -> str:
        """Return Ollama model name for the candidate at *index*.

        Args:
            index: Candidate index (0, 1, 2, ...).
            task_context: Optional TaskContext for risk_based strategy.

        Returns:
            Model name string for Ollama (e.g. "deepseek-r1:7b").
        """
        if self.strategy == "risk_based" and not self.should_use_full_pipeline(task_context):
            model = self._developer_model()
            self._record(model, full=False)
            return model

        if self.strategy == "role_based":
            role = self._role_order[index % len(self._role_order)]
            model = self.models.get(role.value, self._developer_model())
        else:
            # "rotate" — simple round-robin over model values
            model_list = list(self.models.values())
            model = model_list[index % len(model_list)]

        self._record(model, full=True)
        return model

    def should_use_full_pipeline(self, task_context=None) -> bool:
        """Domain routing: skip multi-model for TRIVIAL/SIMPLE tasks.

        For simple tasks, using the developer model alone is sufficient
        and avoids the overhead of loading multiple models.
        """
        if task_context is None:
            return True
        complexity = getattr(task_context, "complexity", None)
        if complexity is None:
            return True
        if hasattr(complexity, "name"):
            complexity = complexity.name
        if hasattr(complexity, "value"):
            complexity = complexity.value
        return str(complexity).upper() not in ("TRIVIAL", "SIMPLE")

    def get_role_for_index(self, index: int) -> TrinityRole:
        """Return the TrinityRole for a given candidate index."""
        return self._role_order[index % len(self._role_order)]

    def get_model_for_role(self, role: TrinityRole) -> str:
        """Return model name for a specific role."""
        return self.models.get(role.value, self._developer_model())

    @property
    def enabled(self) -> bool:
        """Trinity is effective only with 2+ distinct models and not disabled."""
        if getattr(self, '_disabled', False):
            return False
        return len(set(self.models.values())) > 1

    @property
    def model_count(self) -> int:
        return len(set(self.models.values()))

    def get_status(self) -> Dict:
        """Return status dict for /api/trinity/status."""
        return {
            "enabled": self.enabled,
            "strategy": self.strategy,
            "model_count": self.model_count,
            "models": dict(self.models),
            "role_order": [r.value for r in self._role_order],
            "stats": dict(self._stats),
        }

    def _developer_model(self) -> str:
        """Return the developer model (fallback default)."""
        return self.models.get(
            TrinityRole.DEVELOPER.value,
            next(iter(self.models.values())),
        )

    def _record(self, model: str, full: bool) -> None:
        self._stats["selections"] += 1
        if model in self._stats["per_model"]:
            self._stats["per_model"][model] += 1
        if full:
            self._stats["full_pipeline_used"] += 1
        else:
            self._stats["developer_only_used"] += 1


def parse_trinity_models_env(env_value: str) -> Dict[str, str]:
    """Parse QWEN_TRINITY_MODELS env var into a role→model dict.

    Accepted formats:
        "deepseek-r1:7b,qwen2.5-coder:7b,deepseek-coder:6.7b-instruct"
            → maps positionally to architect, developer, reviewer

        "architect=deepseek-r1:7b,developer=qwen2.5-coder:7b,reviewer=deepseek-coder:6.7b-instruct"
            → explicit role assignment
    """
    parts = [p.strip() for p in env_value.split(",") if p.strip()]
    if not parts:
        return {}

    # Check if key=value format
    if "=" in parts[0]:
        result = {}
        for part in parts:
            if "=" in part:
                role, model = part.split("=", 1)
                result[role.strip()] = model.strip()
        return result

    # Positional format: architect, developer, reviewer
    roles = [TrinityRole.ARCHITECT.value, TrinityRole.DEVELOPER.value, TrinityRole.REVIEWER.value]
    return {roles[i]: parts[i] for i in range(min(len(parts), len(roles)))}
